'''
This function can be considered to be a part of the chessengine.py file,
'self' refers to an object of the gamestate class
'''

# Generate all valid moves for the current player
def getValidMoves(self):
        """
        Generates all valid moves for the current player, considering checks, pins, 
        and ensuring the king is not left in check after the move.
        """
        moves = [] # Initialize an empty list to store the valid moves found

        # Determine if the current player is in check, locate any pinned pieces, 
        # and identify the pieces delivering check(s).
        self.inCheck, self.pins, self.checks = self.checkForPinsAndChecks() 

        # Get the current king's location - needed for check and pin validation
        if self.whiteToMove:
            kingRow = self.whiteKingLocation[0]
            kingCol = self.whiteKingLocation[1]
        else:
            kingRow = self.blackKingLocation[0]
            kingCol = self.blackKingLocation[1]

        # --- Handling Checks ---
        if self.inCheck:
            # Scenario 1: Single Check - The king is attacked by exactly one piece.
            if len(self.checks) == 1: 
                # Generate all theoretically possible moves first. 
                # We will then filter them based on the check situation.
                # Note: This might generate moves that don't resolve the check initially.
                moves = self.getAllPossibleMoves() 

                # Get the details of the checking piece and its location
                check = self.checks[0] # Format: (row, col, dx, dy) - dx, dy is direction from king
                checkRow = check[0]
                checkCol = check[1]
                pieceChecking = self.board[checkRow][checkCol] # e.g., 'bR', 'wN'
                
                # Determine the squares where a piece could move to resolve the check.
                # This includes capturing the checking piece or blocking its path (if not a Knight).
                validSquares = [] 
                
                # If the checking piece is a Knight, the only way to stop the check 
                # (besides moving the king) is to capture the Knight.
                if pieceChecking[1] == "N":
                    validSquares = [(checkRow, checkCol)]
                else: 
                    # If it's a sliding piece (Rook, Bishop, Queen), calculate the line of attack.
                    # Any square along this line (between king and attacker, inclusive of attacker) is a potential blocking/capture square.
                    for i in range(1, 8): # Iterate up to 7 squares away
                        # Calculate the coordinates of the square along the attack vector
                        validSquare = (kingRow + check[2] * i, kingCol + check[3] * i) 
                        validSquares.append(validSquare)
                        # Stop once we reach the checking piece's square (it's included)
                        if validSquare[0] == checkRow and validSquare[1] == checkCol:
                            break
                
                # Filter the generated moves: Remove any move that doesn't resolve the check.
                # Iterate backwards because we are removing elements from the list.
                for i in range(len(moves) - 1, -1, -1):
                    # We only need to filter non-king moves here. 
                    # King moves generated by getAllPossibleMoves should already be valid 
                    # (not moving into check), but they also need to not land on an attacked square.
                    # This filtering focuses on blocking or capturing the checker.
                    if moves[i].pieceMoved[1] != 'K': 
                        # If the move's destination square is NOT one of the calculated valid squares 
                        # (either capturing the checker or blocking the attack)...
                        if not (moves[i].endRow, moves[i].endCol) in validSquares:
                            # ...then this move is illegal because it doesn't resolve the check.
                            moves.remove(moves[i])
            
            # Scenario 2: Double Check - The king is attacked by two pieces simultaneously.
            else: 
                # In a double check, blocking or capturing is impossible. 
                # The only possible way out is to move the king.
                self.getKingMoves(kingRow, kingCol, moves) # Generate *only* the valid king moves.

        # Scenario 3: Not in Check - The king is currently safe.
        else: 
            # Generate all possible moves. 
            # Note: self.getAllPossibleMoves() *should* ideally handle pins correctly,
            # otherwise, the commented-out section below would be needed.
            moves = self.getAllPossibleMoves()

        # --- Checkmate and Stalemate Detection ---
        # After generating and filtering all moves, check if any valid moves remain.
        if len(moves) == 0: 
            # If there are no valid moves...
            if self.inCheck:
                # ...and the king is currently in check, it's checkmate.
                self.checkmate = True
            else:
                # ...and the king is *not* in check, it's stalemate.
                self.stalemate = True
        else:
            # If there are valid moves, it's neither checkmate nor stalemate.
            self.checkmate = False
            self.stalemate = False

        # Return the final list of validated, legal moves for the current player.
        return moves